# docker exec -it gpm-vg-b_camunda_1 bash
# open browser with url: http://localhost:8080/camunda-welcome/index.html

version: "3.8"
services:
  camunda:
    image: vgb:0.0.1-SNAPSHOT
    container_name: "camunda"
    ports:
      - "8080:8080"
    volumes:
      - ./target/vgb.war:/camunda/webapps/vgb.war

  psql:
    container_name: gpm-db
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: POSTGRES
      POSTGRES_PASSWORD: POSTGRES
      POSTGRES_DB: GPM
    volumes:
      - psql_vol:/var/lib/postgresql/datas

volumes:
  psql_vol: