### open browser with url:
# http://localhost:8080/camunda/app/admin/default/ for admin interface
# http://localhost:8080/camunda/app/cockpit/default/ for cockpit interface
# http://localhost:8080/camunda/app/tasklist/default/ for tasklist interface
###

version: "3.8"
services:
  camunda:
    build:
      context: .
      dockerfile: docker-data/camunda/Dockerfile
    environment:
      - CAMUNDA_USERNAME=demo
      - CAMUNDA_PASSWORD=demo
      - TZ=Europe/Berlin
      - DB_DRIVER=org.postgresql.Driver
      - DB_URL=jdbc:postgresql://psql:5432/ENGINE
      - DB_USERNAME=POSTGRES
      - DB_PASSWORD=POSTGRES
      - WAIT_FOR=psql:5432
    container_name: "camunda"
    ports:
      - "8080:8080"
    links:
      - psql

  psql:
    container_name: gpm-db
    build:
      context: .
      dockerfile: docker-data/postgres/Dockerfile
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES="GPM","ENGINE"
      - POSTGRES_USER=POSTGRES
      - POSTGRES_PASSWORD=POSTGRES
