version: '3.3'

services:
  psql:
    container_name: gpm-db
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: POSTGRES
      POSTGRES_PASSWORD: POSTGRES
      POSTGRES_DB: GPM
    volumes:
      - psql_vol:/var/lib/postgresql/datas

volumes:
  psql_vol: